### ISSUE TITLE
More primary objective types

### ISSUE THREAD

**Issue by rdbeerman** [rdbeerman/Invasion-of-the-Refugees#23]

**Comment by rdbeerman** [comment]
SA10 site

**Comment by rdbeerman** [comment]
Precision strikes (in a city?)

- Communications tower
- Palace 
- Ship
- Barracks
- Fuel depot
- Command centre

**Comment by rdbeerman** [comment]
Moving targets
- Convoy A to B
- Patrol on road
- Desert patrol

**Comment by rdbeerman** [comment]
Search and destroy

- Current Artillery types
- Camp
- Civilian buildings forming a fortified compound

**Comment by FDR451** [comment]
Regarding moving targets:

How about
