### ISSUE TITLE
Suggestion - Interception Mission

### ISSUE THREAD

**Issue by nadavisr18** [rdbeerman/Invasion-of-the-Refugees#27]
Interception Mission - Have some sort of Russian bomber escorted by a couple Su-27 (for example) heading towards friendly airspace (carrier group, airbase, border etc.) and scramble friendly aircraft to intercept it.
The scrambled friendlies may not shoot at the incoming flight but intercept it to figure out their "intentions".
Enemy flight will have ROE - Do Not Engage until a certain radius of their target and them randomly have them either go offensive or RTB.

if that doesn't make a lot of sense you can ask me (Nada)

**Comment by rdbeerman** [comment]
needs to be synced across all maps

**Comment by rdbeerman** [comment]
Had this on old version of the map, tends to get ignored by players
